name: vista_news
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # state management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5

  # Database
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0
  shared_preferences: ^2.3.2
  path_provider: ^2.1.1

  # sharing
  share_plus: ^10.0.2

  # Network
  chopper: ^7.0.0

  # routing
  go_router: ^14.3.0

  # utils
  flutter_screenutil: ^5.9.3
  url_launcher: ^6.3.1
  permission_handler: ^11.3.1
  network_info_plus: ^6.0.2
  fluttertoast: ^8.2.8
  geolocator: ^13.0.1
  connectivity_plus: ^6.0.5
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  chopper_generator: ^7.0.0
  isar_generator: ^3.1.0
  build_runner: ^2.4.7

  bloc_test: ^9.1.7
  mocktail: ^1.0.4

flutter:
  uses-material-design: true

  assets:
    - assets/
